export const defaultAnnouncement = [
  '<start>',
  'Secure. Contain. Protect.',
  '<rate value="1.1">The Foundation will keep the world</rate> <pitch value="1.2">normal.</pitch>',
  'Every day. Every site. Every anomaly.',
  '<voice pitch="-3" loudness="3" tension="0.2">Warning. Containment breach.</voice>',
  '<voice pitch="-3" loudness="3" tension="0.2">Control is lost.</voice> <pause seconds="0.5"/>',
  '<volume value="0.7">No one can <stutter repeats="2">contain</stutter> it.</volume>',
  'Look familiar? Scenes like this are happening right now.',
  '<pitch value="1.2">You could be next.</pitch>',
  '<pause seconds="0.5"/> Unless you make the most important decision of your life.',
  'Prove your skill. Join the Foundation.',
  'Be part of an elite force that will secure, contain and protect.',
  'See the world as it should be. Normal.',
  'Become the hero. Become the legend.',
  '<fit seconds="2.5">Become Class D.</fit>',
  '<end>',
].join('\n');
