export const defaultAnnouncement = [
  '<start>',
  'Secure. Contain. Protect.',
  '<rate value="1.1">The Foundation will keep the world</rate> <pitch value="1.2">normal.</pitch>',
  'Every day. Every site. Every anomaly.',
  '<voice pitch="-3" loudness="3" tension="0.2">Warning. Containment breach.</voice>',
  '<voice pitch="-3" loudness="3" tension="0.2">Control is lost.</voice> <pause seconds="0.5"/>',
  '<volume value="0.7">No one can <stutter repeats="2">contain</stutter> it.</volume>',
  'Right now, the door is open.',
  '<pitch value="1.2">Someone must close it.</pitch>',
  '<pause seconds="0.5"/> Join the Foundation.',
  'Do not run. Do not wait.',
  'Keep the lights on. Keep the doors shut. Keep the world normal.',
  'Report to your nearest site.',
  '<fit seconds="2.5">Become Class-D.</fit>',
  '<end>',
].join('\n');
